image: python:latest


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VAR_MSG_TEMPLATE: "unset"


cache:
  paths:
    - .cache/pip
    - venv/


before_script:
  - echo $(pwd)
  - python3 --version
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate


stage_json_validator:
  stage: test
  variables:
    VAR_MSG_TEMPLATE: "validator_products_json"
    VAR_CI_JOB_URL: "$CI_JOB_ID"
  tags:
    - linter
  script:
    - printf "$VAR_MSG_TEMPLATE\n" > /tmp/msg_template.json
    - printf "$VAR_CI_JOB_URL\n" > /tmp/msg_filedjob.json
    - echo $(pwd)
    - pip3 install jsonschema
    - python3 buildsystem/validator_products_json.py --products=./products
  timeout: 5m
  when: on_success


stage_ruts_unfinished_validator:
  stage: test
  variables:
    VAR_MSG_TEMPLATE: "validator_unfinished_ruts"
    VAR_CI_JOB_URL: "$CI_JOB_ID"
  tags:
    - linter
  script:
    - printf "$VAR_MSG_TEMPLATE\n" > /tmp/msg_template.json
    - printf "$VAR_CI_JOB_URL\n" > /tmp/msg_filedjob.json
    - echo $(pwd)
    - python3 buildsystem/validator_ruts_unfinished.py --translations=./gui/translations
  timeout: 5m
  needs:
    - job: stage_json_validator
      optional: true
  when: on_success


notify_error:
  stage: .post
  tags:
    - linter
  variables:
    TIME: "10"
    IMDESKTOP_HOST: "https://100.99.5.116/spacetown/notifications/webhook/"
    HTTP_HEADER: "Content-Type: application/json; charset=utf-8"
    VAR_CHAT_ID: "115090@chat.agent" # https://u.internal.myteam.mail.ru/profile/jsons
    JSON_FMT: '{"kind": {"channel": "myteam", "myteam_receiver": "TMPL_RECEIVER", "myteam_sender": "helperbot"}, "template": {"tmpl_name": "TMPL_MSG_TEMPLATE", "git_comment": "$CI_COMMIT_MESSAGE", "branch_name": "$CI_COMMIT_BRANCH", "git_hash": "$CI_COMMIT_SHA", "user_email": "$GITLAB_USER_EMAIL", "job_url": "https://gitlab.corp.mail.ru/instant-messengers/im.desktop/-/jobs/TMPL_CIJOB_TEMPLATE"}}\n'
  script:
    - export MSG_TEMPLATE=$(cat /tmp/msg_template.json); echo "$MSG_TEMPLATE"
    - export MSG_CIJOB=$(cat /tmp/msg_filedjob.json); echo "$MSG_CIJOB"

    - printf "$JSON_FMT" > /tmp/data.json
    - cat /tmp/data.json

    - sed -i "s/TMPL_RECEIVER/$VAR_CHAT_ID/g" /tmp/data.json
    - sed -i "s/TMPL_MSG_TEMPLATE/$MSG_TEMPLATE/g" /tmp/data.json
    - sed -i "s/TMPL_CIJOB_TEMPLATE/$MSG_CIJOB/g" /tmp/data.json

    - cat /tmp/data.json

    - curl -k -X "POST" "$IMDESKTOP_HOST" -H "$HTTP_HEADER" -d @"/tmp/data.json"

  when: on_failure
